# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20200424_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
